# Example data source connection
data_source soda_demo:
  type: postgres
  host: localhost
  username: postgres
  password: secret
  database: postgres
  # Optional configuration to exclude columns from Soda scans
  sampler:
    exclude_columns:
      dim_product: ["large_photo", "*_description"]

# Example Soda platform connection
soda_cloud:
  host: cloud.soda.io
  api_key_id: f9d77945***
  api_key_secret: lk2t783-k***


