# Connect to AdventureWorks example data source 
# https://go.soda.io/connect-ds
data_source adventureworks:
  type: postgres
  connection:
    host: localhost
    username: postgres
    password: secret
  database: postgres
  schema: public
# Connect to your Soda platform account 
soda_cloud:
  host: 
  api_key_id:
  api_key_secret:
